# Generated by Django 5.1.4 on 2024-12-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('OW', 'Outerwear'), ('T', 'Top'), ('B', 'Bottom'), ('CK', 'ChicKicks'), ('A', 'Accessories')], max_length=2)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
